apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    run: thrasher
  name: thrasher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thrasher
    spec:
      containers:
      - image: gcr.io/hightowerlabs/thrasher:0.0.1
        name: thrasher
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 1000m
